# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/nfs
  block:

    - name: Collecting package facts
      become: true
      ansible.builtin.package_facts:
        manager: auto
      when:
        - "ansible_facts.packages is not defined"

    - name: Collecting service facts
      become: true
      ansible.builtin.service_facts:
      when:
        - "ansible_facts.services is not defined"
        - "'nfs-utils' or 'nfs-kernel-server' in ansible_facts.packages"

    - name: CIS | Ensure NFS is not installed
      become: true
      ansible.builtin.package:
        name:
          # RedHat
          - 'nfs-utils'
          # Debian packages
          - 'nfs-kernel-server'
          - 'rpcbind'
        state: absent

    - name: CIS | Ensure the nfs-server service is masked
      become: true
      ansible.builtin.systemd:
        name: 'nfs-server'
        enabled: false
        masked: true
        force: true
      when:
        - "'nfs-utils' or 'nfs-kernel-server' in ansible_facts.packages"
        - "'nfs-server.service' in ansible_facts.services"

    - name: CIS | Ensure the rpcbind is masked
      become: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: false
        masked: true
        force: true
      when:
        - "'rpcbind' in ansible_facts.packages"
      with_items:
        - 'rpcbind.service'
        - 'rpcbind.socket'

  # Tags to be applied to this role (block)
  tags:
    - 'role_foolean_nfs'
