# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/nfs
  block:

    - name: Set OS variables
      ansible.builtin.include_vars:
        file: "{{ item }}"
      with_first_found:
        - "{{ ansible_os_family|lower }}.yml"
        - "default.yml"

    - name: Collecting package facts
      become: true
      ansible.builtin.package_facts:
        manager: auto
      when:
        - "ansible_facts.packages is not defined"

    - name: Collecting service facts
      become: true
      ansible.builtin.service_facts:
      when:
        - "ansible_facts.services is not defined"

    - name: Configure NFS server
      ansible.builtin.import_tasks:
        file: 'server.yml'

    - name: Configure NFS client
      ansible.builtin.import_tasks:
        file: 'client.yml'

    # rpcbind is a common package required by both
    # the server and client packages.
    - name: CIS | Ensure rpcbind is removed
      become: true
      ansible.builtin.package:
        name: 'rpcbind'
        state: absent
      when:
        - not nfs_client_enable and not nfs_server_enable

    - name: CIS | Ensure the rpcbind is masked
      become: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: false
        masked: true
        force: true
      when:
        - "'rpcbind' in ansible_facts.packages or nfs_client_installed.changed"
      with_items:
        - 'rpcbind.service'
        - 'rpcbind.socket'

    # Flush any handlers that we might have called
    - name: Flush handlers
      ansible.builtin.meta:
        flush_handlers

  # Tags to be applied to this role (block)
  tags:
    - 'role_foolean_nfs'
