# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

- name: NFS server disable
  block:
    - name: CIS | Ensure NFS is not installed
      become: true
      ansible.builtin.package:
        name: "{{ nfs_server_packages }}"
        state: absent

    - name: CIS | Ensure the nfs-server service is masked
      become: true
      ansible.builtin.systemd:
        name: 'nfs-server'
        enabled: false
        masked: true
        force: true
      when:
        - "'nfs-utils' or 'nfs-kernel-server' in ansible_facts.packages"
        - "'nfs-server.service' in ansible_facts.services"
  when:
    - not nfs_server_enable

- name: NFS server enable
  block:
    - name: Ensure NFS is installed
      become: true
      ansible.builtin.package:
        name: "{{ nfs_server_packages }}"
        state: present

    # Create a list of clients from the NFS exports object
    - name: Set fact of NFS clients
      ansible.builtin.set_fact:
        clients: |
          [
            {% for export, clients in nfs_server_exports.items()|unique|sort(attribute='0') %}
            {%  for client, options in clients.items()|unique|sort(attribute='0') %}
          "{{ client }}",
            {%  endfor %}
            {% endfor %}
          ]

    - name: Allow inbound NFS
      become: true
      community.general.ufw:
        rule: allow
        src: "{{ item }}"
        direction: 'in'
        port: '2049'
        proto: 'tcp'
        log: true
      with_items: "{{ clients|unique|sort }}"
      when:
        - ansible_os_family|lower == 'debian'
        - nfs_server_exports != None
        - "'ufw' in ansible_facts.packages"

    - name: Configure NFS exports
      become: true
      ansible.builtin.template:
        src: 'etc/exports.j2'
        dest: '/etc/exports'
        owner: 'root'
        group: 'root'
        mode: '0644'
      notify:
        - Reload NFS exports

    - name: Ensure the nfs-server service is enabled
      become: true
      ansible.builtin.systemd:
        name: 'nfs-server'
        enabled: true
        masked: false
        state: started
      when:
        - "'nfs-utils' or 'nfs-kernel-server' in ansible_facts.packages"
        - "'nfs-server.service' in ansible_facts.services"
  when:
    - nfs_server_enable
